### ISSUE TITLE
License Confirmation

### ISSUE THREAD

**Issue by pyfemtet** [deGravity/brepmatching#6]
@deGravity
I hope this message finds you well. We are currently exploring the possibility of modifying the `brepmatching`, `automate`, `breploader` and `parasolid_frustrum` components to incorporate them into our products ([Femtet](https://www.muratasoftware.com/en/) and [PyFemtet](https://pyfemtet.readthedocs.io/en/stable/)).

I found the licensing information about `brepmatching` and `automate` in there `setup.py`, but I could not find the licensing details for `breploader` and `parasolid_frustrum`.
Could you please provide us with the licensing information for these components? Your assistance would be greatly appreciated.

Thank you for your time!

Best regards,
Kazuma NAITO (pyfemtet developer)
Murata Manufacturing Co., Ltd.

**Comment by deGravity** [comment]
`breploader` can be MIT licensed as well. I need to double-check on `parasolid_frustrum` to be sure I'm not accidentally including someone else's code before I make a licensing determination for it.

**Comment by pyfemtet** [comment]
Thank you for your response. I appreciate your efforts in checking the licensing. There is a possibility that we may need to reimplement parasolid_frustrum on our end, so I would like to request that you confirm the license.

I look forward to hearing back from you.

Best regards,

**Comment by deGravity** [comment]
I believe that `parasolid_frustrum` can also be MIT licensed, however I am not a copyright expert, so I am not 100% sure. I wrote all of the code except for the preprocessor definitions for Windows platforms [here](https://github.com/deGravity/parasolid_frustrum/blob/6ccd043c312a6e564c8b63176ca1826c5b3e10bf/frustrum.cpp#L15), which are the same as in Parasolid's example frustrum. Otherwise this was a scratch implementation of a frustrum. I hope this helps!

**Comment by pyfemtet** [comment]
Thank you for confirming the license! After reviewing the code on my end, I found that reimplementing parasolid_frustrum for use with BRepMatching only to predict a pair of parasolids is not too cumbersome, so I proceeded with that implementation.

Currently, the BRepMatching fork from your repository is available at the following URL: https://github.com/pyfemtet/brepmatching.
Please let me know if you have any specific preferences regarding citation.

I will continue development other features while being mindful of the points you mentioned.
Thank you once again for your excellent collaboration!
